service: ds-predict

variablesResolutionMode: 20210326

plugins:
  - serverless-stage-manager
  - serverless-plugin-warmup

custom:
  stages:
    - dev
    - test
    - staging
    - prod
  warmup:
    default:
      enabled: true
      prewarm: true
      timeout: 30
      name: ${self:provider.stage}-ds-predict-warmer
      concurrency: ${self:custom.warmupConcurrency.${self:provider.stage}}
      role: ${opt:role, 'arn:aws:iam::044086777883:role/dataAnalyticsLambdaRole'}
  warmupConcurrency:
    dev: 1
    test: 1
    staging: 1
    prod: 10
  mongoHost:
    dev: dev-cluster.fg2e5.mongodb.net
    test: test-cluster.9mc2r.mongodb.net
    staging: stg-cluster-pl-0.7ljem.mongodb.net
    prod: prd-cluster-pl-0.5rvfa.mongodb.net
  mongoPassword:
    dev: ${ssm:dev-ds-mongodb-password}
    test: ${ssm:test-ds-mongodb-password}
    staging: ${ssm:staging-ds-mongodb-password}
    prod: ${ssm:prod-ds-mongodb-password}
  securityGroupIds:
    dev:
      - sg-0a85d287510c750fb
    test:
      - sg-0821f0b9421d5c942
    staging:
      - sg-0a676a88fdcd07038
    prod:
      - sg-02f9c88c7e05b1f05
  subnetIds:
    dev:
      - subnet-06dd909aac8fd1948
    test:
      - subnet-090044e7a4daccd43
    staging:
      - subnet-07a1a18b1527f00c7
      - subnet-0587b148568217c70
    prod:
      - subnet-0290592d406bccc27
      - subnet-0790d32929fd45c33

provider:
  name: aws
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 256
  timeout: 900
  stackName: ${self:provider.stage}-ds-predict
  logRetentionInDays: 14
  deploymentBucket:
    name: castcle-data-analytics
  iam:
    role: ${opt:role, 'arn:aws:iam::044086777883:role/dataAnalyticsLambdaRole'}
  vpc:
    securityGroupIds: ${self:custom.securityGroupIds.${self:provider.stage}}
    subnetIds: ${self:custom.subnetIds.${self:provider.stage}}
  ecr:
    images:
      app_image:
        uri: REPOSITORY_URI@DIGEST
  environment:
    ENV: ${self:provider.stage}
    MONGO_HOST: ${self:custom.mongoHost.${self:provider.stage}}
    MONGO_PASSWORD: ${self:custom.mongoPassword.${self:provider.stage}}

functions:
  perCtPredictor:
    name: ${self:provider.stage}-ds-predict-per-ct-predictor
    memorySize: 2048
    warmup:
      default:
        enabled: true
    image:
      name: app_image
      command:
        - per_ct_predictor.handle
  friendToFollow:
    name: ${self:provider.stage}-ds-predict-friend-to-follow
    memorySize: 2048
    warmup:
      default:
        enabled: true
    image:
      name: app_image
      command:
        - friend_to_follow.handle
  coldStartPredictor:
    name: ${self:provider.stage}-ds-predict-coldstart-predictor
    memorySize: 2048
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - coldstart_predictor.handle
    events:
      - schedule: cron(*/30 * * * ? *)
  
  sentenceEmbedding:
    name: ${self:provider.stage}-ds-predict-sentence-embedding
    memorySize: 2048
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - sentence_embedding.handle
    events:
      - schedule: cron(*/30 * * * ? *)
